global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: "food-delivery"
    environment: "development"

scrape_configs:
  - job_name: "order-service"
    static_configs:
      - targets: ["order-svc:8080"]
        labels:
          service: "order-svc"
    metrics_path: "/metrics"
    scrape_interval: 10s
